### ISSUE TITLE
can you provide me some infomation ?

### ISSUE THREAD

**Issue by IcerAndroid** [jrummyapps/BuildPropEditor#7]
url "${artifactory_url}"
      credentials {
        username = "${artifactory_username}"
        password = "${artifactory_password}"
      }

**Comment by jaredrummler** [comment]
From the [README](https://github.com/jrummyapps/BuildPropEditor/blob/master/README.md):

> BuildProp Editor has proprietary dependencies. You cannot build the project; it isn't fully open source. However, much of the code is available for your viewing pleasure. Contributions to localize the project are welcome and appreciated.

**Comment by IcerAndroid** [comment]
import com.jrummyapps.android.app.App;
import com.jrummyapps.android.files.FilePermission;
import com.jrummyapps.android.prefs.Prefs;
import com.jrummyapps.android.roottools.RootTools;
import com.jrummyapps.android.roottools.commands.ShellCommand;
import com.jrummyapps.android.storage.Storage;
import com.jrummyapps.android.util.FileUtils;
import com.jrummyapps.android.util.IoUtils;
import com.jrummyapps.android.util.Jot;
import com.jrummyapps.android.util.Toasts;

i want to get some utility class

**Comment by jaredrummler** [comment]
They aren't open source. Maybe one day I will open source everything but for now you can't build the project.

**Comment by IcerAndroid** [comment]
thank you !😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭
